"""
Django settings for TallerMecanico project.

Generated by 'django-admin startproject' using Django 5.1.5.
"""

from pathlib import Path
import os
import dj_database_url  # Asegúrate de tener esto en tu requirements.txt

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-(u$$6imr2-zl&2!2fphx)&iclh#wrnp_0%-lr5dorhljod-5*7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

# Para Render o producción
ALLOWED_HOSTS = ['taller-mecanico.onrender.com', 'localhost', '127.0.0.1']


# Application definition
INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Taller.apps.TallerConfig',
]

JAZZMIN_SETTINGS = {
    "site_title": "Taller Mecánico Admin",
    "site_header": "Panel de Administración",
    "site_brand": "Taller Mecánico",
    "site_logo": "img/carro.gif",
    "welcome_sign": "Bienvenido al panel de administración del taller",
    "copyright": "© 2025 Taller Mecánico",
    "primary_color": "#bd5d38",
    "secondary_color": "#2C2F33",
    "dark_mode_toggle": True,
    "navigation_expanded": True,
    "show_ui_builder": False,
    "custom_css": "static/css/styles.css",
    "icons": {
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "app.Vehiculo": "fas fa-car",
        "app.Reparacion": "fas fa-tools",
        "app.Servicio": "fas fa-cogs",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Recomendado para producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TallerMecanico.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Taller/Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TallerMecanico.wsgi.application'

# Database
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=not DEBUG
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTH_USER_MODEL = 'Taller.Usuario'


# Internationalization
LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'Taller/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Producción con WhiteNoise
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "tallermecanico208@gmail.com"
EMAIL_HOST_PASSWORD = "vtpu glgb ezno ugnc"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
